name: Hello workflows
on:
    push:
        branches: [master]
jobs:
    greet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v4
      - name: print greetings
        run:  echo "Hello from GitHub Actions!"
